# Generated by Django 3.1.3 on 2021-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='цена',
            field=models.IntegerField(default=0),
        ),
    ]
