# Generated by Django 3.1.3 on 2021-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210122_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='год',
            field=models.DateTimeField(),
        ),
    ]
